spring:
  
  application:
    name: sfg-recipe
  
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  
  datasource:
    url: "jdbc:h2:mem:sfg-recipe-db"
    driverClassName: "org.h2.Driver"
    username: sa
    password: password
    
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
